// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD-e1ecmKIGARSpas_z2ONUyRPjpMfecY',
    appId: '1:922365899153:web:02b467a58810a56a75aa30',
    messagingSenderId: '922365899153',
    projectId: 'choifoodapp-b15b3',
    authDomain: 'choifoodapp-b15b3.firebaseapp.com',
    storageBucket: 'choifoodapp-b15b3.firebasestorage.app',
    measurementId: 'G-1Z0C2SGZ57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgmTv9aGUEvMat6wz2_H_pBScrnJqaTCg',
    appId: '1:922365899153:android:de654fc7dffa406d75aa30',
    messagingSenderId: '922365899153',
    projectId: 'choifoodapp-b15b3',
    storageBucket: 'choifoodapp-b15b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi9ZGPE7C2V8_2VpoD6bMw_H-w_loLWMg',
    appId: '1:922365899153:ios:2485bb299715cf9175aa30',
    messagingSenderId: '922365899153',
    projectId: 'choifoodapp-b15b3',
    storageBucket: 'choifoodapp-b15b3.firebasestorage.app',
    iosBundleId: 'com.example.choifood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi9ZGPE7C2V8_2VpoD6bMw_H-w_loLWMg',
    appId: '1:922365899153:ios:2485bb299715cf9175aa30',
    messagingSenderId: '922365899153',
    projectId: 'choifoodapp-b15b3',
    storageBucket: 'choifoodapp-b15b3.firebasestorage.app',
    iosBundleId: 'com.example.choifood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD-e1ecmKIGARSpas_z2ONUyRPjpMfecY',
    appId: '1:922365899153:web:88d2e0d13aaf1cc575aa30',
    messagingSenderId: '922365899153',
    projectId: 'choifoodapp-b15b3',
    authDomain: 'choifoodapp-b15b3.firebaseapp.com',
    storageBucket: 'choifoodapp-b15b3.firebasestorage.app',
    measurementId: 'G-MNR3BH78HY',
  );
}
